spring.application.name=lostandfound
# Server Port
server.port=8080

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/lostandfound
spring.datasource.username=postgres
spring.datasource.password=Shivi@123

# Hibernate Configuration (Auto-creates tables based on our Java classes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Limit upload size to 2MB to prevent server strain
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB



# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=shivamkansal1000@gmail.com
# spring.mail.password=zbkjjqotoclelwgd
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.connectiontimeout=5000
# spring.mail.properties.mail.smtp.timeout=5000
# spring.mail.properties.mail.smtp.writetimeout=5000

# Brevo Email Configuration
brevo.api.key=${BREVO_API_KEY:xkeysib-YOUR_API_KEY_HERE}
brevo.sender.email=${BREVO_SENDER_EMAIL:shivamkansal1000@gmail.com}
brevo.sender.name=${BREVO_SENDER_NAME:RecoverX Lost and Found}

logging.level.com.example.lostandfound=DEBUG

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:qsbqegip}
cloudinary.api-key=${CLOUDINARY_API_KEY:834463542452867}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:bgGgA1FqyoiGNXfWg6uUeoYNLD8}

# Frontend Redirect URL
app.frontend.url=${FRONTEND_URL:http://localhost:5173}





